export const specialities = [
  {
    id: 1,
    name: "Dentist",
    icon: require("../assets/images/dentist.png"),
    url: 1,
  },
  {
    id: 2,
    name: "Neurologist",
    icon: require("../assets/images/neurologist.png"),
    url: 2,
  },
  {
    id: 3,
    name: "Orthopedic",
    icon: require("../assets/images/arthopedic.jpg"),
    url: 3,
  },
  {
    id: 4,
    name: "Cardiologist",
    icon: require("../assets/images/cardiologist.jpg"),
    url: 4,
  },
  {
    id: 5,
    name: "Dermatologist",
    icon: require("../assets/images/Dermatologist.jpg"),
    url: 5,
  },
  {
    id: 6,
    name: "Pediatrician",
    icon: require("../assets/images/Pediatrician.png"),
    url: 6,
  },
  {
    id: 7,
    name: "Psychiatrist",
    icon: require("../assets/images/Psychiatrist.webp"),
    url: 7,
  },
  {
    id: 8,
    name: "Radiologist",
    icon: require("../assets/images/Radiologist.webp"),
    url: 8,
  },
  {
    id: 9,
    name: "Oncologist",
    icon: require("../assets/images/Oncologist.webp"),
    url: 9,
  },
  {
    id: 10,
    name: "ENT Specialist",
    icon: require("../assets/images/ENT_Specialist.webp"),
    url: 10,
  },
  {
    id: 11,
    name: "Gynecologist",
    icon: require("../assets/images/Gynecologist.webp"),
    url: "/pages/specialities/id=11",
  },
  {
    id: 12,
    name: "Allergist",
    icon: require("../assets/images/Allergist.webp"),
    url: "/pages/specialities/id=12",
  },
  {
    id: 13,
    name: "Urologist",
    icon: require("../assets/images/Urologist.webp"),
    url: 13,
  },
  {
    id: 14,
    name: "Gastroenterologist",
    icon: require("../assets/images/Gastroenterologist.png"),
    url: 14,
  },
  {
    name: "Hematologist",
    icon: require("../assets/images/Hematologist.webp"),
    url: 15,
  },
  {
    id: 16,
    name: "Endocrinologist",
    icon: require("../assets/images/Endocrinologist.png"),
    url: 16,
  },
  {
    id: 17,
    name: "Ophthalmologist",
    icon: require("../assets/images/Ophthalmologist.png"),
    url: "/pages/specialities/id=17",
  },
  {
    id: 18,
    name: "Pulmonologist",
    icon: require("../assets/images/Pulmonologist.jpg"),
    url: "/pages/specialities/id=18",
  },
  {
    id: 19,
    name: "Nephrologist",
    icon: require("../assets/images/Nephrologist.webp"),
    url: "/pages/specialities/id=19",
  },
  {
    id: 20,
    name: "Immunologist",
    icon: require("../assets/images/Immunologist.png"),
    url: "/pages/specialities/id=20",
  },
  // {
  //   id: 21,
  //   name: "Rheumatologist",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=21",
  // },
  // {
  //   id: 22,
  //   name: "Pathologist",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=22",
  // },
  // {
  //   id: 23,
  //   name: "Physiotherapist",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=23",
  // },
  // {
  //   id: 24,
  //   name: "General Physician",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=24",
  // },
  // {
  //   id: 25,
  //   name: "Plastic Surgeon",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=25",
  // },
  // {
  //   id: 26,
  //   name: "Cosmetologist",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=26",
  // },
  // {
  //   id: 27,
  //   name: "Podiatrist",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=27",
  // },
  // {
  //   id: 28,
  //   name: "Surgeon",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=28",
  // },
  // {
  //   id: 29,
  //   name: "Emergency Medicine",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=29",
  // },
  // {
  //   id: 30,
  //   name: "Nutritionist",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=30",
  // },
  // {
  //   id: 31,
  //   name: "Occupational Therapist",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=31",
  // },
  // {
  //   id: 32,
  //   name: "Sports Medicine",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=32",
  // },
  // {
  //   id: 33,
  //   name: "Veterinarian",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=33",
  // },
  // {
  //   id: 34,
  //   name: "Forensic Medicine",
  //   icon: require("../assets/images/Endocrinologist.png"),
  //   url: "/pages/specialities/id=34",
  // },
];

export const lab = [];

export const doctors = [
  {
    id: 1,
    name: "Dr. Zara K",
    location: "Coimbatore, India",
    price: "₹50.00 / per slot",
    rating: 4.5,
    specialty: 1,
    lab: 1,
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    url: 1,
    education: {
      school: "MBBS",
      location: "PSG",
      year: "2020",
    },
    service: ["Cleaning", "Repair"],
    experience: {
      name: "Junior Doctor",
      location: "PSG",
      year: "2021",
    },
  },
  {
    id: 2,
    name: "Dr. Waseem Sabra",
    location: "Cherrybrook, Australia",
    price: "₹2.45 / per slot",
    rating: 4.0,
    specialty: 2,
    lab: 2,
    image: "https://randomuser.me/api/portraits/men/47.jpg",
    url: 2,
    education: {
      school: "MBBS",
      location: "PSG",
      year: "2020",
    },
    service: ["Cleaning", "Repair"],
    experience: {
      name: "Junior Doctor",
      location: "PSG",
      year: "2021",
    },
  },
  {
    id: 3,
    name: "Dr. Amanda Li",
    location: "Beijing, China",
    price: "₹80.00 / per slot",
    rating: 4.7,
    specialty: 1,
    lab: 3,
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    url: 3,
    education: {
      school: "MBBS",
      location: "Beijing Medical College",
      year: "2019",
    },
    service: ["Orthopedics", "Physiotherapy"],
    experience: {
      name: "Resident Doctor",
      location: "Beijing General Hospital",
      year: "2020",
    },
  },
  {
    id: 4,
    name: "Dr. Ahmed Khan",
    location: "Lahore, Pakistan",
    price: "₹40.00 / per slot",
    rating: 4.2,
    specialty: 3,
    lab: 4,
    image: "https://randomuser.me/api/portraits/men/58.jpg",
    url: 4,
    education: {
      school: "MBBS",
      location: "King Edward Medical University",
      year: "2018",
    },
    service: ["Cardiology"],
    experience: {
      name: "Cardiologist",
      location: "Punjab Institute of Cardiology",
      year: "2019",
    },
  },
  {
    id: 5,
    name: "Dr. Lisa Monroe",
    location: "Berlin, Germany",
    price: "₹60.00 / per slot",
    rating: 4.8,
    specialty: 4,
    lab: 5,
    image: "https://randomuser.me/api/portraits/women/95.jpg",
    url: 5,
    education: {
      school: "MD",
      location: "Berlin University",
      year: "2021",
    },
    service: ["Dermatology", "Skin Treatment"],
    experience: {
      name: "Dermatologist",
      location: "Berlin Skin Institute",
      year: "2022",
    },
  },
  {
    id: 6,
    name: "Dr. Rajeev Singh",
    location: "New Delhi, India",
    price: "₹55.00 / per slot",
    rating: 4.1,
    specialty: 2,
    lab: 6,
    image: "https://randomuser.me/api/portraits/men/35.jpg",
    url: 6,
    education: {
      school: "MBBS",
      location: "AIIMS Delhi",
      year: "2017",
    },
    service: ["Pediatrics"],
    experience: {
      name: "Pediatrician",
      location: "Max Healthcare",
      year: "2018",
    },
  },
  {
    id: 7,
    name: "Dr. Emily Johnson",
    location: "New York, USA",
    price: "₹90.00 / per slot",
    rating: 4.9,
    specialty: 1,
    lab: 7,
    image: "https://randomuser.me/api/portraits/women/41.jpg",
    url: 7,
    education: {
      school: "MD",
      location: "Harvard Medical School",
      year: "2016",
    },
    service: ["General Medicine"],
    experience: {
      name: "Physician",
      location: "Mount Sinai Hospital",
      year: "2017",
    },
  },
  {
    id: 8,
    name: "Dr. Hassan Iqbal",
    location: "Dubai, UAE",
    price: "₹70.00 / per slot",
    rating: 4.6,
    specialty: 5,
    lab: 8,
    image: "https://randomuser.me/api/portraits/men/78.jpg",
    url: 8,
    education: {
      school: "MBBS",
      location: "Dubai Medical University",
      year: "2020",
    },
    service: ["Neurology"],
    experience: {
      name: "Neurologist",
      location: "Dubai Neurology Center",
      year: "2021",
    },
  },
  {
    id: 9,
    name: "Dr. Aisha Yusuf",
    location: "Lagos, Nigeria",
    price: "₹30.00 / per slot",
    rating: 4.3,
    specialty: 3,
    lab: 9,
    image: "https://randomuser.me/api/portraits/women/88.jpg",
    url: 9,
    education: {
      school: "MBBS",
      location: "University of Lagos",
      year: "2015",
    },
    service: ["Family Medicine"],
    experience: {
      name: "General Practitioner",
      location: "Lagos University Teaching Hospital",
      year: "2016",
    },
  },
  {
    id: 10,
    name: "Dr. Carl Müller",
    location: "Vienna, Austria",
    price: "₹85.00 / per slot",
    rating: 4.4,
    specialty: 4,
    lab: 10,
    image: "https://randomuser.me/api/portraits/men/12.jpg",
    url: 10,
    education: {
      school: "MD",
      location: "Medical University of Vienna",
      year: "2013",
    },
    service: ["Oncology"],
    experience: {
      name: "Oncologist",
      location: "Vienna Oncology Institute",
      year: "2014",
    },
  },
  {
    id: 11,
    name: "Dr. Mei Tan",
    location: "Tokyo, Japan",
    price: "₹100.00 / per slot",
    rating: 4.9,
    specialty: 5,
    lab: 11,
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    url: 11,
    education: {
      school: "MD",
      location: "University of Tokyo",
      year: "2018",
    },
    service: ["Psychiatry"],
    experience: {
      name: "Psychiatrist",
      location: "Tokyo Psychiatry Center",
      year: "2019",
    },
  },
  {
    id: 12,
    name: "Dr. John Smith",
    location: "London, UK",
    price: "₹75.00 / per slot",
    rating: 4.5,
    specialty: 2,
    lab: 12,
    image: "https://randomuser.me/api/portraits/men/39.jpg",
    url: 12,
    education: {
      school: "MD",
      location: "University of Oxford",
      year: "2017",
    },
    service: ["Cardiology"],
    experience: {
      name: "Cardiologist",
      location: "London Cardiology Clinic",
      year: "2018",
    },
  },
  {
    id: 13,
    name: "Dr. Sara Mendez",
    location: "Madrid, Spain",
    price: "₹65.00 / per slot",
    rating: 4.7,
    specialty: 3,
    lab: 13,
    image: "https://randomuser.me/api/portraits/women/62.jpg",
    url: 13,
    education: {
      school: "MBBS",
      location: "University of Madrid",
      year: "2019",
    },
    service: ["Orthopedics"],
    experience: {
      name: "Orthopedic Surgeon",
      location: "Madrid Orthopedic Center",
      year: "2020",
    },
  },
  {
    id: 14,
    name: "Dr. Ibrahim Omar",
    location: "Cairo, Egypt",
    price: "₹45.00 / per slot",
    rating: 4.2,
    specialty: 4,
    lab: 14,
    image: "https://randomuser.me/api/portraits/men/25.jpg",
    url: 14,
    education: {
      school: "MBBS",
      location: "Cairo University",
      year: "2014",
    },
    service: ["Pediatrics"],
    experience: {
      name: "Pediatrician",
      location: "Cairo Children’s Hospital",
      year: "2015",
    },
  },
  {
    id: 15,
    name: "Dr. Fatima Rahman",
    location: "Dhaka, Bangladesh",
    price: "₹50.00 / per slot",
    rating: 4.6,
    specialty: 2,
    lab: 15,
    image: "https://randomuser.me/api/portraits/women/77.jpg",
    url: 15,
    education: {
      school: "MBBS",
      location: "Dhaka Medical College",
      year: "2020",
    },
    service: ["Family Medicine", "General Consultation"],
    experience: {
      name: "General Practitioner",
      location: "Dhaka General Hospital",
      year: "2021",
    },
  },
];

export const appointments = [
  { id: 1, patient: "John Doe", status: "Confirmed", date: "2024-12-10" },
  { id: 2, patient: "Jane Smith", status: "Pending", date: "2024-12-11" },
  { id: 3, patient: "Alice Brown", status: "Cancelled", date: "2024-12-12" },
];
